### ISSUE TITLE
Add custom effectiveness table as a GM-configurable option to override default type effectiveness

### ISSUE THREAD

**Issue by GSV-a-Nest-of-Kindled-Embers** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#130]
Add custom effectiveness table as a GM-configurable option to override default type effectiveness.

Assign this to me and I'll do it as a PR.

Messy notes for myself below, please ignore:

overwrite the values in game.ptu.TypeEffectiveness
then refresh all actors to recalc after system init if needed:
game.actors.forEach(a => a.prepareData())

**Comment by dylanpiera** [comment]
Will require #127 or will force users to refresh, otherwise it'll only update on GM side.

Keep in mind Void that you'll also have to implement the on-system-init change based on the settings.

Since 0.8 allows you to save Objects as settings, should probably save the whole TypeEffectiveness array as an object instead, so that's loaded in, instead of being overwritten, which will save having to refresh all the data on system startup

(instead of system loads in default -> all actors are loaded in -> `game.ptu.TypeEffectiveness` is overwritten -> all actor data needs to be relaoded)
(system loads based on `settings.get("ptu", "type-effectiveness")` -> all actors are loaded in)

**Comment by dylanpiera** [comment]
The Custom Type system was implemented a while ago on development.
