### ISSUE TITLE
Add default stages

### ISSUE THREAD

**Issue by caffyn** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#133]
Pokemon could probably use default stages for effects such as Ace Trainer.

**Comment by dylanpiera** [comment]
@caffyn this can be achieved by setting an effect on a Pokémon.

F.e:
![image](https://user-images.githubusercontent.com/2012848/122040448-17271780-cdd8-11eb-9560-19b0d0ea2490.png)

In the future the AE window will be updated to have dropdown options instead of having to manually select what kind of stat you're changing. But for now you'll have to manually fill in the path, being `data.stats.[STAT].stage`
