### ISSUE TITLE
Pokemon Display Names

### ISSUE THREAD

**Issue by Azurespider101** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#146]
So I know there's an option for Characters and custom made actors to change your display name to "Hovered by Anyone".  This is something changeable by default so all created tokens have that option. 

When dropping in Pokemon from the dex i cant change how their tokens are on default. So everytime i drop in a pokemon i have to change its name to hovered by anyone instead of auto display. This is primarily an issue with visual clutter especially when you have multiple pokemon next to each other, flanking and overlapping where the name is just over the pokemon. Especially in melee range i don't want to have someone's name overlapping a token. This is a minor issue of course but tedious to keep having to change the setting. I'm not sure why the Pokemon i drag in have their vision match the default settings, but not the name visibility. 

Also as a separate issue if possible could the font accessibility be a campaign setting instead of a player preference. Or the player preference be the pixel font instead. I find it bulky and clunky

**Comment by dylanpiera** [comment]
> When dropping in Pokemon from the dex i cant change how their tokens are on default.

Foundry has resolved this by adding "Default Token Configurations". If you go to "Configure Settings, the third option will be this Default Token Configurations, and change the setting there. The system's generation just uses the defaults.

> Also as a separate issue if possible could the font accessibility be a campaign setting instead of a player preference. Or the player preference be the pixel font instead. I find it bulky and clunky

I'm not sure if I understand your problem here, the "Font Accessability" option is a player option, so any player/DM can personally decide whether they want it on or not.
