### ISSUE TITLE
Capability "Split Evolution" seems to be granted to many other Mons other than Wurmple

### ISSUE THREAD

**Issue by MetaDK** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#147]
Split Evolution is a capability that indicates that wurmple can have two evolution options, I noticed before that it was tacked onto a Mon that shouldn't have it (can't remember which) and just now noticed that Pikachu also have that one auto-assigned when using Dex Drag-In to generate Pikachus.

**Comment by dylanpiera** [comment]
Hey @MetaDK, this is because the Capability "Split Evolution" is for any pokemon with split evolution, it was just opted by the data source we used to give Wurmple as an example. 

I suppose we can just remove the word 'wurmple' and the amount of evolution options, but this capability is for all Pokémon with split evolutions, including Pikachu.
