### ISSUE TITLE
Pin Missile move won't roll damage

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#187]
The Pin Missile move can show details but won't work when asked to perform the move

 Issue opened on Discord by Urdarum#9926

**Comment by Muhsigbokz** [comment]
Reason:

`module/combat/effects/move_sounds.js:GetMoveSoundPath` checks specifically for the Pin Missile` move to do some logic for playing different sounds depending on how many of the Five Strike hits actually connected. I assume this was done as first test for the more general case of all Five Strike Moves.

If the move is `Pin Missile`, the variable `fiveStrikeCount` is attempted to be read, but it was never defined, causing the function to crash. Because this is called before any Chat Messages are rendered etc., the whole Move vanishes in an Error visible in the Console.
