### ISSUE TITLE
Check capture calculation rules

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#223]
Calc is wrong.

 Issue opened on Discord by AsheEon#0380

**Comment by Muhsigbokz** [comment]
I'll look into it.
For reference, here is a Macro that we use in our campaign that does the trick for all we know.

```js
const ten = ["Burned", "Frozen", "Paralysis", "Poisoned", "Badly Poisoned", "Slowed"]
const fifteen = ["Stuck"]
const round_turn_regex = /^R[0-9]* - T[0-9]*:/
const order_training_regex = /^[A-Z][a-z]* (Order|Training)/

canvas.tokens.controlled.filter(token => token.actor.data.data.species).forEach((token, index) => {
  const actor = token.actor
  let cr = 100
  let mods_html = ""


  //Evo
  const speciesName = actor.data.data.species
  console.log(speciesName)
  const species = game.ptu.GetSpeciesData(speciesName)
  console.log(species)
  const currentStage = species.Evolution.filter(evo => evo[1].toUpperCase() == speciesName.toUpperCase())[0][0]
  console.log(currentStage)
  let arr = species.Evolution.map(a => a[0]).sort((a,b)=> a-b)
  console.log(arr)
  const maxStageOfLine = arr[arr.length-1]
  // -10 if max, 0 if one under, 10 if two under...
  const evoMod = (maxStageOfLine - currentStage ) * 10 - 10
  mods_html += `<tr><td>${maxStageOfLine - currentStage} Evos left</td><td>${evoMod}</td></tr>\n`
  cr+=evoMod

  //Level
  const level = actor.data.data.level.current
  mods_html += `<tr><td>Level ${level}</td><td>-${level*2}</td></tr>\n`
  cr -= level*2

  //HP
  const ratio = actor.data.data.health.value / actor.data.data.health.max
  if (ratio >0.75 ) {
    mods_html += `<tr><td>HP over 75%</td><td>-30</td></tr>\n`
    cr -= 30
  } else if (ratio >0.5 ) {
    mods_html += `<tr><td>HP over 50%</td><td>-15</td></tr>\n`
    cr -= 15
  } else if (ratio >0.25 ) {
    mods_html += `<tr><td>HP over 25%</td><td>+-0</td></tr>\n`
    cr -= 0
  } else if (actor.data.data.health.value > 1) {
    mods_html += `<tr><td>HP over 1</td><td>+15</td></tr>\n`
    cr += 15
  } else {
    mods_html += `<tr><td>HP at 1</td><td>+30</td></tr>\n`
    cr += 30
  }

  // Injuries
  const injuries = actor.data.data.health.injuries
  cr += injuries * 5
    mods_html += `<tr><td>${injuries} Injuries</td><td>${injuries * 5}</td></tr>\n`


  //Effects
  actor.effects.forEach((effect, nothing) => {
    const label = effect.data.label
    if(fifteen.includes(label)){
      mods_html += `<tr><td>${label}</td><td>+15</td></tr>\n`
      cr += 15
    } else if (ten.includes(label)) {
      mods_html += `<tr><td>${label}</td><td>+10</td></tr>\n`
      cr += 10
    } else if (round_turn_regex.test(label)) {
      mods_html += `<tr><td>${label}</td><td>/Move/</td></tr>\n`
      cr += 0
    } else if (order_training_regex.test(label)) {
      mods_html += `<tr><td>${label}</td><td>/OrTr/</td></tr>\n`
      cr += 0
    } else {
      mods_html += `<tr><td>${label}</td><td>+5</td></tr>\n`
      cr += 5
    }
  });
  
  const msg = `<table>
  <tr><td>Pokemon</td><td>${actor.data.name}</td></tr>
  <tr><td>Base</td><td>100</td></tr>
  ${mods_html}
  <tr><td>---</td><td>---</td></tr>
  <tr><td>Total w/o Shiny</td><td>${cr}</td></tr>
  </table>`

  ChatMessage.create({
    whisper: ChatMessage.getWhisperRecipients('GM'),
    content: msg});
});
```

**Comment by Muhsigbokz** [comment]
I assume it should stay the non-errata base 100 way.

**Comment by Muhsigbokz** [comment]
I read over the calculation twice so far.

From what I have seen, what the code *intents* to do seems correct. The only two things seem to be the Quick Ball going `[-20, +5, +10, +20]` instead of `[-20, -15, -10, 0]` and the missing implementation for the  Repeat Ball. 

Anything else known that needs fixing?

**Comment by Muhsigbokz** [comment]
As far as I can see, both the Trainer and 'Mon Level are included both visually and mathematically.
https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/blob/c2d5a3331a2c309af22194a8360955b879700ad1/module/utils/pokeball-capture-calculations.js#L97
![image](https://user-images.githubusercontent.com/101654076/178585320-c3af25ae-073a-4b9a-8682-8bbc46394fb3.png)

**Comment by Muhsigbokz** [comment]
Regarding the Repeat Ball
![image](https://user-images.githubusercontent.com/101654076/178586662-332ed954-2deb-4251-b997-aa2eff44193a.png)

I see multiple ways to implement this:
1. Check all Pokémon owned by the capturing Trainer, check species. If any has the same as target, grant bonus.
2. Check the capturing Trainers Pokédex. If it has the entry for the capturée (now that is a word) with `owned` set, grant the bonus.
3. Check all Pokémon owned by the capturing Trainer, check species. If any has the same as target or a later one of the Evolution Line, grant bonus.

I do not see one of those options definitely better than the other for an overwhelming majority of groups. some might go for living Dex, some Dex as registered, some might not care about the Dex because they use Milestone Exp only. 

This is why I would implement the Repeat Ball with a Prompt for the GM like the other more complexly conditioned Pokéballs.

Are you fine with that?

**Comment by dylanpiera** [comment]
> As far as I can see, both the Trainer and 'Mon Level are included both visually and mathematically.
> https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/blob/c2d5a3331a2c309af22194a8360955b879700ad1/module/utils/pokeball-capture-calculations.js#L97
> ![image](https://user-images.githubusercontent.com/101654076/178585320-c3af25ae-073a-4b9a-8682-8bbc46394fb3.png)
> 

Gonna have to check this tomorrow, something weird happened for sure in my game.

**Comment by Muhsigbokz** [comment]
@dylanpiera Did you find anything else?

**Comment by dylanpiera** [comment]
I've not had the time to check this yet but will asap.
