### ISSUE TITLE
Condense Defense Curl move description

### ISSUE THREAD

**Issue by dylanpiera** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#409]
Defense Curl move description currently includes "September Playtest" aspect. Suggest condensing the description to remove "September Playtest" in line with Rules Consolidation, but keep the additional effect.

 Issue opened on Discord by joooooosh#0000

**Comment by joosh98** [comment]
Now fixed in PTR-Data. The effect is the same, just worded more succinctly.

Before:
The user becomes Curled Up. While Curled Up, the user becomes immune to Critical Hits and gains 10 Damage Reduction. However, while Curled Up, the user is Slowed and their Accuracy is lowered by 4. The user may stop being Curled Up as a Swift Action. If the user has Rollout or Ice Ball in their Move List, they do not become Slowed while Curled Up. Furthermore, when using the Moves Rollout or Ice Ball while Curled Up, the user gains a +10 bonus to the damage rolls of those Moves and does not suffer Accuracy Penalties from being Curled Up.\\nSeptember Playtest: The user's Defense is raised 1 Combat Stage and they become Curled Up until the end of the Scene or they are Recalled or Take a Breather. When using the Moves Rollout or Ice Ball while Curled Up, the user gains a +10 bonus to the damage rolls of those Moves.

After:
The user becomes Curled Up. While Curled Up, the user becomes immune to Critical Hits, and gains 10 Damage Reduction and +1 Defense Combat Stage. However, while Curled Up, the user is Slowed and their Accuracy is lowered by 4. The user may stop being Curled Up as a Swift Action, or if they are Recalled or Take a Breather. If the user has Rollout or Ice Ball in their Move List, they do not become Slowed while Curled Up, and the user gains a +10 bonus to the damage rolls of those Moves and does not suffer Accuracy Penalties from being Curled Up.
