### ISSUE TITLE
Allow certain moves to be used while sleeping

### ISSUE THREAD

**Issue by Tinkastrong** [dylanpiera/Foundry-Pokemon-Tabletop-United-System#527]
Snore and Sleep Talk come to mind.

[Screencast from 2023-11-05 10-40-08.webm](https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System/assets/149251521/9e137f09-9354-4638-be2e-0447422d7dce)

**Comment by dylanpiera** [comment]
Implemented `self:ignore:sleep` as a roll-option that ignores the sleep disabling effect. Instead of applying this *only* to things like snore/sleep talk, as sleep talk allows you to use another move; we'd either have to fully automate sleep talk or it'd be tedious to temporarily add the sleep ignoring rule to that move. So I just elected to make the actor completely able to ignore sleep disabled if they have this option.

**Comment by dylanpiera** [comment]
Added in Beta 16

**Comment by Tinkastrong** [comment]
> Implemented `self:ignore:sleep` as a roll-option that ignores the sleep disabling effect. Instead of applying this _only_ to things like snore/sleep talk, as sleep talk allows you to use another move; we'd either have to fully automate sleep talk or it'd be tedious to temporarily add the sleep ignoring rule to that move. So I just elected to make the actor completely able to ignore sleep disabled if they have this option.

I thought there is a predicate like `move:sleep-talk` that allows for such effects to only trigger if the current context indicates that move.
